### ISSUE TITLE
Core framework improvements

### ISSUE THREAD

**Issue by rmrsk** [chombo-discharge/chombo-discharge#328]
Operators:

- [x] EBCoarAve (in #329)
- [x] EBLeastSquaresMultigridInterpolator (in #329)
- [x] AggEBPWLFillPatch (in #329)
- [x] EBFineInterp (in #329)
- [x] EBFluxRegister (in #329)
- [x] EBLevelRedist (in #329)
- [x] EBCoarToFineRedist (in #329)
- [x] EBCoarToCoarRedist (in #329)
- [x] EBFineToCoarRedist (in #329)
- [x] EBGradient (in #329)
- [x] EBMGInterp (in #329)
- [x] EBMGProlong (in #329)
- [x] EBAMRParticleMesh (in #329)
- [x] EBAMRSurfaceDeposition (in #329)
- [x] EBCoarseFineParticleMesh (in #329)

Multigrid improvements:

- [x] Tunable SOR relaxation factor (pass in through EBHelmholtzOp and solvers that use it? (in #329, hidden option for EBHelmholtzOp)
- [x] Reduce number of flux calculations, coarsenings, and inhomogenous interpolations (in #329)
- [x] Improve box aggregation for deeper multigrid (in #329)
- [x] alloc/dealloc multigrid temporaries (not done because memory peak came from cut-cell stencils - which can be BIG)

Misc:
- [x] writePlotFile, avoid extra memory allocations (in #329)
- [x] Figure out ItoKMC restart issue (in #329)
- [x] EBCoarAve and EBGhostCellInterpolator should use AggStencil for performance (in #329)
- [x] Watch memory in FieldSolver - some temporaries can be deleted (in #329)
- [x] Ditch the per-nanosecond timing in the grid report
- [x] CdrPlasmaGodunovStepper only need to compute plot variables when writing the plot file...
- [x] Ask Chombo devs about HDF memory strain - simulations crash during file writes (run valgrind)
- [x] Delete buffers but keep Copiers in the EB operators
- [x] Reduce memory during regrids (solvers/AMR should deallocate unnecessary memory)
- [x] CdrPlasmaPhysics needs a memory shave.
- [x] Remove evictInvalidParticles and simply remap from finest level to coarsest (like we do with remap())
- [x] Add documentation about CH_TIMER and Timer. DO NOT USE Timer at large concurrencies!!! Remove Timer profiles from all input files
- [x] Get rid of m_scratch from ItoSolver. Fix BrownianWalkerStepper since it expects this to hold the PPC
- [x] Fix PIC filter
- [x] Fix levelOp copiers and optimizations for both EBHelmholtzOp and MFHelmholtzOp
- [x] Get rid of of TGA and EBBackwardEuler for EddingtonSP1. Run our own versions of these, ala CdrMultigrid, with controllable terminatino criteria.
- [x] Run regression and convergence tests.
- [ ] Run performance timing on Betzy for sprite example. Does multigrid require more optimizations?
